---

- include: environment.yml
  when: mode == "env"

- include: build.yml
  when: mode == "build"

- include: fresh-install.yml
  when: mode == "fresh-install"

- include: deploy.yml
  when: mode == "deploy"
